# Generated by Django 4.0.4 on 2022-05-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogues',
            fields=[
                ('QANumber', models.AutoField(primary_key=True, serialize=False)),
                ('UserTEXT', models.CharField(max_length=516)),
                ('BotTEXT', models.CharField(max_length=1024)),
            ],
        ),
    ]
